version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "uv"
    directory: "/backend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "bun"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆
