/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as UserRouteImport } from './routes/_user'
import { Route as UserIndexRouteImport } from './routes/_user/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as AdminAdminRouteImport } from './routes/admin/_admin'
import { Route as UserTeamRouteImport } from './routes/_user/team'
import { Route as UserSettingsRouteImport } from './routes/_user/settings'
import { Route as UserScoreboardRouteImport } from './routes/_user/scoreboard'
import { Route as UserChallengesRouteImport } from './routes/_user/challenges'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/_admin/users'
import { Route as AdminAdminTeamsRouteImport } from './routes/admin/_admin/teams'
import { Route as AdminAdminTagsRouteImport } from './routes/admin/_admin/tags'
import { Route as AdminAdminSubmissionsRouteImport } from './routes/admin/_admin/submissions'
import { Route as AdminAdminSettingsRouteImport } from './routes/admin/_admin/settings'
import { Route as AdminAdminScoreboardRouteImport } from './routes/admin/_admin/scoreboard'
import { Route as AdminAdminScoreAdjustmentsRouteImport } from './routes/admin/_admin/score-adjustments'
import { Route as AdminAdminSchedulerRouteImport } from './routes/admin/_admin/scheduler'
import { Route as AdminAdminPluginsRouteImport } from './routes/admin/_admin/plugins'
import { Route as AdminAdminPagesRouteImport } from './routes/admin/_admin/pages'
import { Route as AdminAdminOauthProvidersRouteImport } from './routes/admin/_admin/oauth-providers'
import { Route as AdminAdminOauthClientsRouteImport } from './routes/admin/_admin/oauth-clients'
import { Route as AdminAdminNotificationsRouteImport } from './routes/admin/_admin/notifications'
import { Route as AdminAdminLinksRouteImport } from './routes/admin/_admin/links'
import { Route as AdminAdminFilesRouteImport } from './routes/admin/_admin/files'
import { Route as AdminAdminEventsRouteImport } from './routes/admin/_admin/events'
import { Route as AdminAdminCustomFieldsRouteImport } from './routes/admin/_admin/custom-fields'
import { Route as AdminAdminChallengesRouteImport } from './routes/admin/_admin/challenges'
import { Route as AdminAdminCategoriesRouteImport } from './routes/admin/_admin/categories'
import { Route as UserPSlugRouteImport } from './routes/_user/p.$slug'
import { Route as UserChallengesChallengeIdRouteImport } from './routes/_user/challenges_.$challengeId'
import { Route as AdminAdminUsersUserIdRouteImport } from './routes/admin/_admin/users_.$userId'
import { Route as AdminAdminTeamsTeamIdRouteImport } from './routes/admin/_admin/teams_.$teamId'
import { Route as AdminAdminSchedulerJobIdRouteImport } from './routes/admin/_admin/scheduler_.$jobId'
import { Route as AdminAdminPagesPageIdRouteImport } from './routes/admin/_admin/pages_.$pageId'
import { Route as AdminAdminChallengesChallengeIdRouteImport } from './routes/admin/_admin/challenges_.$challengeId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/_user',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRoute = AdminAdminRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const UserTeamRoute = UserTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => UserRoute,
} as any)
const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => UserRoute,
} as any)
const UserScoreboardRoute = UserScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => UserRoute,
} as any)
const UserChallengesRoute = UserChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => UserRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTeamsRoute = AdminAdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTagsRoute = AdminAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSubmissionsRoute = AdminAdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSettingsRoute = AdminAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminScoreboardRoute = AdminAdminScoreboardRouteImport.update({
  id: '/scoreboard',
  path: '/scoreboard',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminScoreAdjustmentsRoute =
  AdminAdminScoreAdjustmentsRouteImport.update({
    id: '/score-adjustments',
    path: '/score-adjustments',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminSchedulerRoute = AdminAdminSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPluginsRoute = AdminAdminPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminPagesRoute = AdminAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminOauthProvidersRoute =
  AdminAdminOauthProvidersRouteImport.update({
    id: '/oauth-providers',
    path: '/oauth-providers',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminOauthClientsRoute = AdminAdminOauthClientsRouteImport.update({
  id: '/oauth-clients',
  path: '/oauth-clients',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminNotificationsRoute = AdminAdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminLinksRoute = AdminAdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminFilesRoute = AdminAdminFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminEventsRoute = AdminAdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCustomFieldsRoute = AdminAdminCustomFieldsRouteImport.update({
  id: '/custom-fields',
  path: '/custom-fields',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminChallengesRoute = AdminAdminChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminCategoriesRoute = AdminAdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminAdminRoute,
} as any)
const UserPSlugRoute = UserPSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => UserRoute,
} as any)
const UserChallengesChallengeIdRoute =
  UserChallengesChallengeIdRouteImport.update({
    id: '/challenges_/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => UserRoute,
  } as any)
const AdminAdminUsersUserIdRoute = AdminAdminUsersUserIdRouteImport.update({
  id: '/users_/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminTeamsTeamIdRoute = AdminAdminTeamsTeamIdRouteImport.update({
  id: '/teams_/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminSchedulerJobIdRoute =
  AdminAdminSchedulerJobIdRouteImport.update({
    id: '/scheduler_/$jobId',
    path: '/scheduler/$jobId',
    getParentRoute: () => AdminAdminRoute,
  } as any)
const AdminAdminPagesPageIdRoute = AdminAdminPagesPageIdRouteImport.update({
  id: '/pages_/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => AdminAdminRoute,
} as any)
const AdminAdminChallengesChallengeIdRoute =
  AdminAdminChallengesChallengeIdRouteImport.update({
    id: '/challenges_/$challengeId',
    path: '/challenges/$challengeId',
    getParentRoute: () => AdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof UserIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/challenges': typeof UserChallengesRoute
  '/scoreboard': typeof UserScoreboardRoute
  '/settings': typeof UserSettingsRoute
  '/team': typeof UserTeamRoute
  '/admin': typeof AdminAdminRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/challenges/$challengeId': typeof UserChallengesChallengeIdRoute
  '/p/$slug': typeof UserPSlugRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/custom-fields': typeof AdminAdminCustomFieldsRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/files': typeof AdminAdminFilesRoute
  '/admin/links': typeof AdminAdminLinksRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/oauth-clients': typeof AdminAdminOauthClientsRoute
  '/admin/oauth-providers': typeof AdminAdminOauthProvidersRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/plugins': typeof AdminAdminPluginsRoute
  '/admin/scheduler': typeof AdminAdminSchedulerRoute
  '/admin/score-adjustments': typeof AdminAdminScoreAdjustmentsRoute
  '/admin/scoreboard': typeof AdminAdminScoreboardRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/tags': typeof AdminAdminTagsRoute
  '/admin/teams': typeof AdminAdminTeamsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/challenges/$challengeId': typeof AdminAdminChallengesChallengeIdRoute
  '/admin/pages/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/scheduler/$jobId': typeof AdminAdminSchedulerJobIdRoute
  '/admin/teams/$teamId': typeof AdminAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/challenges': typeof UserChallengesRoute
  '/scoreboard': typeof UserScoreboardRoute
  '/settings': typeof UserSettingsRoute
  '/team': typeof UserTeamRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/': typeof UserIndexRoute
  '/challenges/$challengeId': typeof UserChallengesChallengeIdRoute
  '/p/$slug': typeof UserPSlugRoute
  '/admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/custom-fields': typeof AdminAdminCustomFieldsRoute
  '/admin/events': typeof AdminAdminEventsRoute
  '/admin/files': typeof AdminAdminFilesRoute
  '/admin/links': typeof AdminAdminLinksRoute
  '/admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/oauth-clients': typeof AdminAdminOauthClientsRoute
  '/admin/oauth-providers': typeof AdminAdminOauthProvidersRoute
  '/admin/pages': typeof AdminAdminPagesRoute
  '/admin/plugins': typeof AdminAdminPluginsRoute
  '/admin/scheduler': typeof AdminAdminSchedulerRoute
  '/admin/score-adjustments': typeof AdminAdminScoreAdjustmentsRoute
  '/admin/scoreboard': typeof AdminAdminScoreboardRoute
  '/admin/settings': typeof AdminAdminSettingsRoute
  '/admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/tags': typeof AdminAdminTagsRoute
  '/admin/teams': typeof AdminAdminTeamsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/challenges/$challengeId': typeof AdminAdminChallengesChallengeIdRoute
  '/admin/pages/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/scheduler/$jobId': typeof AdminAdminSchedulerJobIdRoute
  '/admin/teams/$teamId': typeof AdminAdminTeamsTeamIdRoute
  '/admin/users/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_user': typeof UserRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_user/challenges': typeof UserChallengesRoute
  '/_user/scoreboard': typeof UserScoreboardRoute
  '/_user/settings': typeof UserSettingsRoute
  '/_user/team': typeof UserTeamRoute
  '/admin/_admin': typeof AdminAdminRouteWithChildren
  '/oauth/consent': typeof OauthConsentRoute
  '/_user/': typeof UserIndexRoute
  '/_user/challenges_/$challengeId': typeof UserChallengesChallengeIdRoute
  '/_user/p/$slug': typeof UserPSlugRoute
  '/admin/_admin/categories': typeof AdminAdminCategoriesRoute
  '/admin/_admin/challenges': typeof AdminAdminChallengesRoute
  '/admin/_admin/custom-fields': typeof AdminAdminCustomFieldsRoute
  '/admin/_admin/events': typeof AdminAdminEventsRoute
  '/admin/_admin/files': typeof AdminAdminFilesRoute
  '/admin/_admin/links': typeof AdminAdminLinksRoute
  '/admin/_admin/notifications': typeof AdminAdminNotificationsRoute
  '/admin/_admin/oauth-clients': typeof AdminAdminOauthClientsRoute
  '/admin/_admin/oauth-providers': typeof AdminAdminOauthProvidersRoute
  '/admin/_admin/pages': typeof AdminAdminPagesRoute
  '/admin/_admin/plugins': typeof AdminAdminPluginsRoute
  '/admin/_admin/scheduler': typeof AdminAdminSchedulerRoute
  '/admin/_admin/score-adjustments': typeof AdminAdminScoreAdjustmentsRoute
  '/admin/_admin/scoreboard': typeof AdminAdminScoreboardRoute
  '/admin/_admin/settings': typeof AdminAdminSettingsRoute
  '/admin/_admin/submissions': typeof AdminAdminSubmissionsRoute
  '/admin/_admin/tags': typeof AdminAdminTagsRoute
  '/admin/_admin/teams': typeof AdminAdminTeamsRoute
  '/admin/_admin/users': typeof AdminAdminUsersRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/admin/_admin/challenges_/$challengeId': typeof AdminAdminChallengesChallengeIdRoute
  '/admin/_admin/pages_/$pageId': typeof AdminAdminPagesPageIdRoute
  '/admin/_admin/scheduler_/$jobId': typeof AdminAdminSchedulerJobIdRoute
  '/admin/_admin/teams_/$teamId': typeof AdminAdminTeamsTeamIdRoute
  '/admin/_admin/users_/$userId': typeof AdminAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/challenges'
    | '/scoreboard'
    | '/settings'
    | '/team'
    | '/admin'
    | '/oauth/consent'
    | '/challenges/$challengeId'
    | '/p/$slug'
    | '/admin/categories'
    | '/admin/challenges'
    | '/admin/custom-fields'
    | '/admin/events'
    | '/admin/files'
    | '/admin/links'
    | '/admin/notifications'
    | '/admin/oauth-clients'
    | '/admin/oauth-providers'
    | '/admin/pages'
    | '/admin/plugins'
    | '/admin/scheduler'
    | '/admin/score-adjustments'
    | '/admin/scoreboard'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tags'
    | '/admin/teams'
    | '/admin/users'
    | '/admin/'
    | '/admin/challenges/$challengeId'
    | '/admin/pages/$pageId'
    | '/admin/scheduler/$jobId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/challenges'
    | '/scoreboard'
    | '/settings'
    | '/team'
    | '/oauth/consent'
    | '/'
    | '/challenges/$challengeId'
    | '/p/$slug'
    | '/admin/categories'
    | '/admin/challenges'
    | '/admin/custom-fields'
    | '/admin/events'
    | '/admin/files'
    | '/admin/links'
    | '/admin/notifications'
    | '/admin/oauth-clients'
    | '/admin/oauth-providers'
    | '/admin/pages'
    | '/admin/plugins'
    | '/admin/scheduler'
    | '/admin/score-adjustments'
    | '/admin/scoreboard'
    | '/admin/settings'
    | '/admin/submissions'
    | '/admin/tags'
    | '/admin/teams'
    | '/admin/users'
    | '/admin'
    | '/admin/challenges/$challengeId'
    | '/admin/pages/$pageId'
    | '/admin/scheduler/$jobId'
    | '/admin/teams/$teamId'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/_user'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/_user/challenges'
    | '/_user/scoreboard'
    | '/_user/settings'
    | '/_user/team'
    | '/admin/_admin'
    | '/oauth/consent'
    | '/_user/'
    | '/_user/challenges_/$challengeId'
    | '/_user/p/$slug'
    | '/admin/_admin/categories'
    | '/admin/_admin/challenges'
    | '/admin/_admin/custom-fields'
    | '/admin/_admin/events'
    | '/admin/_admin/files'
    | '/admin/_admin/links'
    | '/admin/_admin/notifications'
    | '/admin/_admin/oauth-clients'
    | '/admin/_admin/oauth-providers'
    | '/admin/_admin/pages'
    | '/admin/_admin/plugins'
    | '/admin/_admin/scheduler'
    | '/admin/_admin/score-adjustments'
    | '/admin/_admin/scoreboard'
    | '/admin/_admin/settings'
    | '/admin/_admin/submissions'
    | '/admin/_admin/tags'
    | '/admin/_admin/teams'
    | '/admin/_admin/users'
    | '/admin/_admin/'
    | '/admin/_admin/challenges_/$challengeId'
    | '/admin/_admin/pages_/$pageId'
    | '/admin/_admin/scheduler_/$jobId'
    | '/admin/_admin/teams_/$teamId'
    | '/admin/_admin/users_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  UserRoute: typeof UserRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AdminAdminRoute: typeof AdminAdminRouteWithChildren
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user': {
      id: '/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/': {
      id: '/_user/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_user/team': {
      id: '/_user/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof UserTeamRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/settings': {
      id: '/_user/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/scoreboard': {
      id: '/_user/scoreboard'
      path: '/scoreboard'
      fullPath: '/scoreboard'
      preLoaderRoute: typeof UserScoreboardRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/challenges': {
      id: '/_user/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof UserChallengesRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/users': {
      id: '/admin/_admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/teams': {
      id: '/admin/_admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminAdminTeamsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/tags': {
      id: '/admin/_admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminAdminTagsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/submissions': {
      id: '/admin/_admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminAdminSubmissionsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/settings': {
      id: '/admin/_admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminAdminSettingsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/scoreboard': {
      id: '/admin/_admin/scoreboard'
      path: '/scoreboard'
      fullPath: '/admin/scoreboard'
      preLoaderRoute: typeof AdminAdminScoreboardRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/score-adjustments': {
      id: '/admin/_admin/score-adjustments'
      path: '/score-adjustments'
      fullPath: '/admin/score-adjustments'
      preLoaderRoute: typeof AdminAdminScoreAdjustmentsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/scheduler': {
      id: '/admin/_admin/scheduler'
      path: '/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AdminAdminSchedulerRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/plugins': {
      id: '/admin/_admin/plugins'
      path: '/plugins'
      fullPath: '/admin/plugins'
      preLoaderRoute: typeof AdminAdminPluginsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/pages': {
      id: '/admin/_admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminAdminPagesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/oauth-providers': {
      id: '/admin/_admin/oauth-providers'
      path: '/oauth-providers'
      fullPath: '/admin/oauth-providers'
      preLoaderRoute: typeof AdminAdminOauthProvidersRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/oauth-clients': {
      id: '/admin/_admin/oauth-clients'
      path: '/oauth-clients'
      fullPath: '/admin/oauth-clients'
      preLoaderRoute: typeof AdminAdminOauthClientsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/notifications': {
      id: '/admin/_admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminAdminNotificationsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/links': {
      id: '/admin/_admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminAdminLinksRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/files': {
      id: '/admin/_admin/files'
      path: '/files'
      fullPath: '/admin/files'
      preLoaderRoute: typeof AdminAdminFilesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/events': {
      id: '/admin/_admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminAdminEventsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/custom-fields': {
      id: '/admin/_admin/custom-fields'
      path: '/custom-fields'
      fullPath: '/admin/custom-fields'
      preLoaderRoute: typeof AdminAdminCustomFieldsRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/challenges': {
      id: '/admin/_admin/challenges'
      path: '/challenges'
      fullPath: '/admin/challenges'
      preLoaderRoute: typeof AdminAdminChallengesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/categories': {
      id: '/admin/_admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminAdminCategoriesRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/_user/p/$slug': {
      id: '/_user/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof UserPSlugRouteImport
      parentRoute: typeof UserRoute
    }
    '/_user/challenges_/$challengeId': {
      id: '/_user/challenges_/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/challenges/$challengeId'
      preLoaderRoute: typeof UserChallengesChallengeIdRouteImport
      parentRoute: typeof UserRoute
    }
    '/admin/_admin/users_/$userId': {
      id: '/admin/_admin/users_/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminAdminUsersUserIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/teams_/$teamId': {
      id: '/admin/_admin/teams_/$teamId'
      path: '/teams/$teamId'
      fullPath: '/admin/teams/$teamId'
      preLoaderRoute: typeof AdminAdminTeamsTeamIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/scheduler_/$jobId': {
      id: '/admin/_admin/scheduler_/$jobId'
      path: '/scheduler/$jobId'
      fullPath: '/admin/scheduler/$jobId'
      preLoaderRoute: typeof AdminAdminSchedulerJobIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/pages_/$pageId': {
      id: '/admin/_admin/pages_/$pageId'
      path: '/pages/$pageId'
      fullPath: '/admin/pages/$pageId'
      preLoaderRoute: typeof AdminAdminPagesPageIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
    '/admin/_admin/challenges_/$challengeId': {
      id: '/admin/_admin/challenges_/$challengeId'
      path: '/challenges/$challengeId'
      fullPath: '/admin/challenges/$challengeId'
      preLoaderRoute: typeof AdminAdminChallengesChallengeIdRouteImport
      parentRoute: typeof AdminAdminRoute
    }
  }
}

interface UserRouteChildren {
  UserChallengesRoute: typeof UserChallengesRoute
  UserScoreboardRoute: typeof UserScoreboardRoute
  UserSettingsRoute: typeof UserSettingsRoute
  UserTeamRoute: typeof UserTeamRoute
  UserIndexRoute: typeof UserIndexRoute
  UserChallengesChallengeIdRoute: typeof UserChallengesChallengeIdRoute
  UserPSlugRoute: typeof UserPSlugRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserChallengesRoute: UserChallengesRoute,
  UserScoreboardRoute: UserScoreboardRoute,
  UserSettingsRoute: UserSettingsRoute,
  UserTeamRoute: UserTeamRoute,
  UserIndexRoute: UserIndexRoute,
  UserChallengesChallengeIdRoute: UserChallengesChallengeIdRoute,
  UserPSlugRoute: UserPSlugRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface AdminAdminRouteChildren {
  AdminAdminCategoriesRoute: typeof AdminAdminCategoriesRoute
  AdminAdminChallengesRoute: typeof AdminAdminChallengesRoute
  AdminAdminCustomFieldsRoute: typeof AdminAdminCustomFieldsRoute
  AdminAdminEventsRoute: typeof AdminAdminEventsRoute
  AdminAdminFilesRoute: typeof AdminAdminFilesRoute
  AdminAdminLinksRoute: typeof AdminAdminLinksRoute
  AdminAdminNotificationsRoute: typeof AdminAdminNotificationsRoute
  AdminAdminOauthClientsRoute: typeof AdminAdminOauthClientsRoute
  AdminAdminOauthProvidersRoute: typeof AdminAdminOauthProvidersRoute
  AdminAdminPagesRoute: typeof AdminAdminPagesRoute
  AdminAdminPluginsRoute: typeof AdminAdminPluginsRoute
  AdminAdminSchedulerRoute: typeof AdminAdminSchedulerRoute
  AdminAdminScoreAdjustmentsRoute: typeof AdminAdminScoreAdjustmentsRoute
  AdminAdminScoreboardRoute: typeof AdminAdminScoreboardRoute
  AdminAdminSettingsRoute: typeof AdminAdminSettingsRoute
  AdminAdminSubmissionsRoute: typeof AdminAdminSubmissionsRoute
  AdminAdminTagsRoute: typeof AdminAdminTagsRoute
  AdminAdminTeamsRoute: typeof AdminAdminTeamsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminChallengesChallengeIdRoute: typeof AdminAdminChallengesChallengeIdRoute
  AdminAdminPagesPageIdRoute: typeof AdminAdminPagesPageIdRoute
  AdminAdminSchedulerJobIdRoute: typeof AdminAdminSchedulerJobIdRoute
  AdminAdminTeamsTeamIdRoute: typeof AdminAdminTeamsTeamIdRoute
  AdminAdminUsersUserIdRoute: typeof AdminAdminUsersUserIdRoute
}

const AdminAdminRouteChildren: AdminAdminRouteChildren = {
  AdminAdminCategoriesRoute: AdminAdminCategoriesRoute,
  AdminAdminChallengesRoute: AdminAdminChallengesRoute,
  AdminAdminCustomFieldsRoute: AdminAdminCustomFieldsRoute,
  AdminAdminEventsRoute: AdminAdminEventsRoute,
  AdminAdminFilesRoute: AdminAdminFilesRoute,
  AdminAdminLinksRoute: AdminAdminLinksRoute,
  AdminAdminNotificationsRoute: AdminAdminNotificationsRoute,
  AdminAdminOauthClientsRoute: AdminAdminOauthClientsRoute,
  AdminAdminOauthProvidersRoute: AdminAdminOauthProvidersRoute,
  AdminAdminPagesRoute: AdminAdminPagesRoute,
  AdminAdminPluginsRoute: AdminAdminPluginsRoute,
  AdminAdminSchedulerRoute: AdminAdminSchedulerRoute,
  AdminAdminScoreAdjustmentsRoute: AdminAdminScoreAdjustmentsRoute,
  AdminAdminScoreboardRoute: AdminAdminScoreboardRoute,
  AdminAdminSettingsRoute: AdminAdminSettingsRoute,
  AdminAdminSubmissionsRoute: AdminAdminSubmissionsRoute,
  AdminAdminTagsRoute: AdminAdminTagsRoute,
  AdminAdminTeamsRoute: AdminAdminTeamsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminChallengesChallengeIdRoute: AdminAdminChallengesChallengeIdRoute,
  AdminAdminPagesPageIdRoute: AdminAdminPagesPageIdRoute,
  AdminAdminSchedulerJobIdRoute: AdminAdminSchedulerJobIdRoute,
  AdminAdminTeamsTeamIdRoute: AdminAdminTeamsTeamIdRoute,
  AdminAdminUsersUserIdRoute: AdminAdminUsersUserIdRoute,
}

const AdminAdminRouteWithChildren = AdminAdminRoute._addFileChildren(
  AdminAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  UserRoute: UserRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AdminAdminRoute: AdminAdminRouteWithChildren,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
