"""add user_agent_sightings

Revision ID: 048c21e479cc
Revises: 04b72631c67f
Create Date: 2026-10-07 12:43:01.180508

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "048c21e479cc"
down_revision: str | None = "04b72631c67f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_agent_sightings",
        sa.Column("user_agent", sa.String(length=512), nullable=False),
        sa.Column("ua_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "cookie", "token", name="clientsource", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=True),
        sa.Column("token_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["token_id"], ["user_tokens.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "source", "ua_hash", name="uq_user_agent_sighting"
        ),
    )
    op.create_index(
        op.f("ix_user_agent_sightings_last_seen_at"),
        "user_agent_sightings",
        ["last_seen_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_user_agent_sightings_last_seen_at"), table_name="user_agent_sightings"
    )
    op.drop_table("user_agent_sightings")
    # ### end Alembic commands ###
