"""cascade user-owned rows on user delete

Revision ID: 25660b8d8760
Revises: ced6f31ce51e
Create Date: 2026-08-17 14:26:44.980816

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25660b8d8760"
down_revision: str | None = "ced6f31ce51e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("oauth_accounts", "user_tokens"):
        name = f"{table}_user_id_fkey"
        op.drop_constraint(name, table, type_="foreignkey")
        op.create_foreign_key(
            name, table, "users", ["user_id"], ["id"], ondelete="CASCADE"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table in ("user_tokens", "oauth_accounts"):
        name = f"{table}_user_id_fkey"
        op.drop_constraint(name, table, type_="foreignkey")
        op.create_foreign_key(name, table, "users", ["user_id"], ["id"])
    # ### end Alembic commands ###
