"""add allowed_roles to oauth_server_clients

Revision ID: dc7034f26882
Revises: 16800b9e9b86
Create Date: 2026-06-28 07:13:25.577691

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dc7034f26882"
down_revision: Union[str, None] = "16800b9e9b86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "oauth_server_clients", sa.Column("allowed_roles", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("oauth_server_clients", "allowed_roles")
    # ### end Alembic commands ###
